name: Test release

on:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  test_linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linux-version:
        - ubuntu:20.04
        - ubuntu:22.04
        - debian:buster
        - debian:bullseye
        - centos:stream8
        - amazonlinux:2022
        node-version: [ 16, 18, 20, 21 ]
        include:
          - linux-version: fedora:36
            node-version: 18
          - linux-version: fedora:37
            node-version: 18
          - linux-version: fedora:38
            node-version: 20
        exclude:
          - linux-version: centos:stream8
            node-version: 21

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - run: npm run container release ${{ matrix.linux-version }} ${{ matrix.node-version }}
      env:
        MOCHA_TEST_NETWORK: 1


  test_winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ windows-2019, macos-11 ]
        node-version: [ 16.x, 18.x, 20.x, 21.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: npm install --ignore-scripts
    - run: npm install node-gyp
    - run: npx @mapbox/node-pre-gyp install
    - run: npx yatag
    - run: npm test
      env:
        MOCHA_TEST_NETWORK: 1
